export const HOME = '/'
export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const BROWSE = '/browse'
export const ADD_SPACE = '/add-space'
export const PROFILE = '/profile'
export const HELP = '/help'
export const SPACE = '/space'